import type { InferInsertModel } from "drizzle-orm"
import type { menu } from "@/db/schema"

type MenuSeed = InferInsertModel<typeof menu>

export const defaultMenuSeeds: MenuSeed[] = [
  // ==================== 工作台 ====================
  {
    id: "menu-workspace",
    label: "menu.workspace",
    icon: "lucide:layout-dashboard",
    sort: 10,
    defaultOpen: true,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-workspace-dashboard",
    label: "menu.dashboard",
    icon: "lucide:gauge",
    to: "/aigate/dashboard",
    parentId: "menu-workspace",
    sort: 1,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },

  // ==================== AI 资产管理 ====================
  {
    id: "menu-assets",
    label: "menu.aiAssets",
    icon: "lucide:package",
    sort: 20,
    defaultOpen: true,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-assets-agents",
    label: "menu.agents",
    icon: "lucide:bot",
    to: "/aigate/agents",
    parentId: "menu-assets",
    sort: 1,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-assets-prompts",
    label: "menu.prompts",
    icon: "lucide:message-square-text",
    to: "/aigate/prompts",
    parentId: "menu-assets",
    sort: 2,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-assets-mcp",
    label: "menu.mcpTools",
    icon: "lucide:wrench",
    to: "/aigate/mcp-tools",
    parentId: "menu-assets",
    sort: 3,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-assets-kb",
    label: "menu.knowledgeBase",
    icon: "lucide:library-big",
    to: "/aigate/knowledge-base",
    parentId: "menu-assets",
    sort: 4,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },

  // ==================== 网关配置 ====================
  {
    id: "menu-gateway",
    label: "menu.gateway",
    icon: "lucide:network",
    sort: 30,
    defaultOpen: false,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-gateway-overview",
    label: "menu.gatewayOverview",
    icon: "lucide:activity",
    to: "/aigate/gateway",
    parentId: "menu-gateway",
    sort: 0,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-gateway-models",
    label: "menu.models",
    icon: "lucide:boxes",
    to: "/aigate/models",
    parentId: "menu-gateway",
    sort: 1,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-gateway-channels",
    label: "menu.channels",
    icon: "lucide:route",
    to: "/aigate/channels",
    parentId: "menu-gateway",
    sort: 2,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-gateway-keys",
    label: "menu.apiKeys",
    icon: "lucide:key-round",
    to: "/aigate/api-keys",
    parentId: "menu-gateway",
    sort: 3,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },

  // ==================== 运营中心 ====================
  {
    id: "menu-ops",
    label: "menu.operations",
    icon: "lucide:activity",
    sort: 40,
    defaultOpen: false,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-ops-billing",
    label: "menu.billing",
    icon: "lucide:receipt",
    to: "/aigate/billing",
    parentId: "menu-ops",
    sort: 1,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-ops-logs",
    label: "menu.apiLogs",
    icon: "lucide:scroll-text",
    to: "/aigate/api-logs",
    parentId: "menu-ops",
    sort: 2,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-ops-alerts",
    label: "menu.alerts",
    icon: "lucide:bell",
    to: "/aigate/alerts",
    parentId: "menu-ops",
    sort: 3,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },

  // ==================== 系统设置 ====================
  {
    id: "menu-settings",
    label: "menu.systemSettings",
    icon: "lucide:settings",
    sort: 90,
    defaultOpen: false,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-settings-users",
    label: "menu.userManage",
    icon: "lucide:user-cog",
    to: "/system-settings/user-manage",
    parentId: "menu-settings",
    sort: 1,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-settings-roles",
    label: "menu.roleManage",
    icon: "lucide:shield",
    to: "/system-settings/role-manage",
    parentId: "menu-settings",
    sort: 2,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-settings-menus",
    label: "menu.menuManage",
    icon: "lucide:menu",
    to: "/system-settings/menu-manage",
    parentId: "menu-settings",
    sort: 3,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-settings-org",
    label: "menu.orgStructure",
    icon: "lucide:building-2",
    to: "/aigate/organizations",
    parentId: "menu-settings",
    sort: 4,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-settings-i18n",
    label: "menu.i18n",
    icon: "lucide:languages",
    to: "/system-settings/internalization",
    parentId: "menu-settings",
    sort: 5,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },
  {
    id: "menu-settings-logs",
    label: "menu.operationLog",
    icon: "lucide:history",
    to: "/system-settings/operation-log",
    parentId: "menu-settings",
    sort: 6,
    enabled: true,
    keepAlive: true,
    permissions: 0,
  },

  // ==================== Hub ====================
  {
    id: "menu-hub",
    label: "menu.hub",
    icon: "lucide:sparkles",
    sort: 100,
    defaultOpen: false,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-hub-overview",
    label: "menu.hubOverview",
    icon: "lucide:home",
    to: "/hub/overview",
    parentId: "menu-hub",
    sort: 1,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-hub-releases",
    label: "menu.releases",
    icon: "lucide:tag",
    to: "/hub/releases",
    parentId: "menu-hub",
    sort: 2,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
  {
    id: "menu-hub-api-docs",
    label: "menu.apiDocs",
    icon: "lucide:book-open-text",
    to: "/docs/api",
    parentId: "menu-hub",
    sort: 3,
    enabled: true,
    keepAlive: false,
    permissions: 0,
  },
]

export async function seedDefaultMenus(db: typeof import("@/db/drizzle").db) {
  const { count } = await import("drizzle-orm")
  const { menu } = await import("@/db/schema")

  const [{ value }] = await db.select({ value: count() }).from(menu)
  if (value > 0) {
    return { seeded: false, count: value }
  }

  await db.insert(menu).values(defaultMenuSeeds)
  return { seeded: true, count: defaultMenuSeeds.length }
}
