export const MCP_MARKETPLACE_PRESETS = [
  {
    id: 'preset-github',
    name: 'GitHub MCP',
    description: '访问 GitHub 仓库、Issues 和 PR',
    vendor: 'GitHub',
    type: 'sse',
    category: 'dev',
    endpoint: 'https://api.githubcopilot.com/mcp/',
  },
  {
    id: 'preset-filesystem',
    name: 'Filesystem MCP',
    description: '本地文件系统读写操作',
    vendor: 'Anthropic',
    type: 'stdio',
    category: 'utility',
    endpoint: 'npx @modelcontextprotocol/server-filesystem',
  },
  {
    id: 'preset-postgres',
    name: 'PostgreSQL MCP',
    description: 'PostgreSQL 数据库查询与管理',
    vendor: 'Community',
    type: 'stdio',
    category: 'database',
    endpoint: 'npx @modelcontextprotocol/server-postgres',
  },
  {
    id: 'preset-brave',
    name: 'Brave Search MCP',
    description: 'Web 搜索能力',
    vendor: 'Brave',
    type: 'sse',
    category: 'search',
    endpoint: 'https://mcp.brave.com/sse',
  },
  {
    id: 'preset-slack',
    name: 'Slack MCP',
    description: 'Slack 消息与频道管理',
    vendor: 'Slack',
    type: 'sse',
    category: 'communication',
    endpoint: 'https://slack.com/api/mcp',
  },
  {
    id: 'preset-google-drive',
    name: 'Google Drive MCP',
    description: 'Google Drive 文件访问',
    vendor: 'Google',
    type: 'sse',
    category: 'storage',
    endpoint: 'https://www.googleapis.com/drive/v3/mcp',
  },
  {
    id: 'preset-puppeteer',
    name: 'Puppeteer MCP',
    description: '浏览器自动化与网页抓取',
    vendor: 'Community',
    type: 'stdio',
    category: 'automation',
    endpoint: 'npx @modelcontextprotocol/server-puppeteer',
  },
  {
    id: 'preset-memory',
    name: 'Memory MCP',
    description: '持久化记忆存储',
    vendor: 'Community',
    type: 'stdio',
    category: 'utility',
    endpoint: 'npx @modelcontextprotocol/server-memory',
  },
  {
    id: 'preset-fetch',
    name: 'Fetch MCP',
    description: 'HTTP 请求工具',
    vendor: 'Community',
    type: 'stdio',
    category: 'utility',
    endpoint: 'npx @modelcontextprotocol/server-fetch',
  },
  {
    id: 'preset-git',
    name: 'Git MCP',
    description: 'Git 仓库操作',
    vendor: 'Community',
    type: 'stdio',
    category: 'dev',
    endpoint: 'npx @modelcontextprotocol/server-git',
  },
]
